### ISSUE TITLE
lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed

### ISSUE THREAD

**Issue by garfieldhoang** [hertg/lightdm-neon#14]
Hi **_hertg_**

Thanks for developing such great theme.
I'm having problem with authentication. After entering the password and hit the next button, it keep looping and nothing really happend.
The log show like this. Could you please help me out?

![issue](https://user-images.githubusercontent.com/114420718/213382567-049646e7-ceb7-44cf-9e5b-ac5e015e5137.png)

**Comment by hertg** [comment]
Hi @garfieldhoang. Sorry for the late response, life is happening.

I have just updated to the latest version of nody-greeter `1.5.2` to try to reproduce but wasn't able to.
To me it seems like this would rather be an issue on nody-greeter's side rather than the theme, did other themes work for you? You could try updating / reinstalling [nody-greeter](https://github.com/JezerM/nody-greeter) or try replacing it with [web-greeter](https://github.com/JezerM/web-greeter) if it still doesn't work.

**Comment by D3vil0p3r** [comment]
> Hi @garfieldhoang. Sorry for the late response, life is happening.
> 
> I have just updated to the latest version of nody-greeter `1.5.2` to try to reproduce but wasn't able to. To me it seems like this would rather be an issue on nody-greeter's side rather than the theme, did other themes work for you? You could try updating / reinstalling [nody-greeter](https://github.com/JezerM/nody-greeter) or try replacing it with [web-greeter](https://github.com/JezerM/web-greeter) if it still doesn't work.

Hello @hertg , I'm using [web-greeter](https://github.com/JezerM/web-greeter) and I'm getting the same issue described above. I tested by the **gruvbox** theme (that should be the default one on web-greeter) and it works correctly.

Tested by **nody-greeter** and it works. So there should be something missing either in the theme for **web-greeter** or in **web-greeter** self despite **gruvbox** theme works there.

I take advantage of this to ask a question:

Is it possible to edit the text and other theme settings directly on some files instead of changing theme by interacting with the theme at login? If so, how is it possible?

UPDATE: just noted that the changes done by the user on the theme are stored in `/var/lib/lightdm/.local/share/web-greeter/QtWebEngine/Default/Local\ Storage/` that maintains a database. So, I guess if the user deletes this folder, the theme will apply the text (and other settings) defined in `/usr/share/web-greeter/themes/neon/bundle.js`.

**Comment by D3vil0p3r** [comment]
@hertg did you get a chance to give a look on this issue?

**Comment by hertg** [comment]
@D3vil0p3r I was not able to reproduce the issue unfortunately, and I can't find obvious issues in the code.

Here is the code for password submit:
https://github.com/hertg/lightdm-neon/blob/6644299558197a2e3aaa115f0df5ec0bb2c34773/src/pages/PasswordPrompt.svelte#L33-L38

Here is the code where lightdm signals are handled:
https://github.com/hertg/lightdm-neon/blob/6644299558197a2e3aaa115f0df5ec0bb2c34773/src/signals.ts#L8-L35

Also note that the original poster reported the issue occurring on **nody-greeter** where in your report it seems to specifically only happen in **web-greeter**. So it seems to be not an issue specific to one greeter, but also not one that is universally reproducible. It would be helpful if you could provide some logs from the greeter. And maybe try to enable debug mode in the web-greeter config file and  then open the developer tools on the login screen and see if you can extract any useful info from the Javascript console.

---

> Is it possible to edit the text and other theme settings directly on some files instead of changing theme by interacting with the theme at login? If so, how is it possible?

That possibility is not considered, the settings are stored to local storage, the default settings are hardcoded in the theme source code here:

https://github.com/hertg/lightdm-neon/blob/6644299558197a2e3aaa115f0df5ec0bb2c34773/src/store/settings.ts#L28-L41

There could be a possibility to implement a feature where those default settings are loaded from a config file instead of being hardcoded in the source code. You could open up a feature request for that, I'd also happily accept PRs.

**Comment by D3vil0p3r** [comment]
I reinstalled it and it works now by web-greeter.
