### ISSUE TITLE
AUR package returns error

### ISSUE THREAD

**Issue by D3vil0p3r** [hertg/lightdm-neon#15]
By building https://aur.archlinux.org/packages/lightdm-theme-neon by `makepkg -si` command, we get:
```
/home/athena/test/lightdm-theme-neon/PKGBUILD: line 23: cd: lightdm-theme-neon: No such file or directory
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by hertg** [comment]
You're right, I hopefully have some time on the weekend to check it out. For the time being you could use the `lightdm-theme-neon-bin` package, it's [built via CI](https://github.com/hertg/lightdm-neon/actions/runs/3569278338) and works. Sorry for the inconvenience.

**Comment by D3vil0p3r** [comment]
Thank you for the answer. I can wait this weekend to get this fix ^^

**Comment by hertg** [comment]
It should be fixed with version `0.2.2` now, let me know if the problem still persists for you.

**Comment by xiota** [comment]
I just saw the PKGBUILD update.  There is still an issue.  `$srcdir` should be guarded by quotes because it can contain spaces.  In general, it's good practice to guard all variables by quotes, especially paths, to prevent potential issues.

https://github.com/hertg/lightdm-neon/blob/e5ae54bbd4caad58da4d738aefa0d1ecb706d6b0/.ci/generate-pkgbuild.sh#L31

https://github.com/hertg/lightdm-neon/blob/e5ae54bbd4caad58da4d738aefa0d1ecb706d6b0/.ci/generate-pkgbuild.sh#L41

https://github.com/hertg/lightdm-neon/blob/e5ae54bbd4caad58da4d738aefa0d1ecb706d6b0/.ci/generate-pkgbuild.sh#L69

**Comment by hertg** [comment]
I pushed an update that guards the `$srcdir`, gonna leave it at that, it's 2.30am where I am :)
