### ISSUE TITLE
[FEATURE] Adding Cyberhype font

### ISSUE THREAD

**Issue by D3vil0p3r** [hertg/lightdm-neon#19]
On the initial text of the theme, is it possible to implement this further font https://freefontdl.com/cyberhype-font/ ?

**Comment by hertg** [comment]
It should be fairly easy to add new fonts. However, I'm not sure if the font you linked to would look that great with the "neon sign effect" that I'm adding to the sign. The fonts I implemented were purposefully selected to be ones that consist of fairly narrow strokes, so that they can be made to look like a a sign made of fluorescent tubes.

**Comment by D3vil0p3r** [comment]
> It should be fairly easy to add new fonts. However, I'm not sure if the font you linked to would look that great with the "neon sign effect" that I'm adding to the sign. The fonts I implemented were purposefully selected to be ones that consist of fairly narrow strokes, so that they can be made to look like a a sign made of fluorescent tubes.

Oh ok. I was imaging that font also on other possible backgrounds, but it is up to you ^^. Feel free to close as unplanned if you prefer to not implement it.
