### ISSUE TITLE
Option to disable AM/PM text and switch to military time

### ISSUE THREAD

**Issue by K0-RR** [hertg/lightdm-neon#23]
Greetings from Europe :)
Could this be implemented to the settings?

**Comment by hertg** [comment]
The method used to get the clock display is `theme_utils.get_current_localized_date()`, which takes the system locale. According to the docs linked below, you could either adapt your system locale, or you can configure it via the greeter config file.

https://web-greeter-page.vercel.app/docs/api/ThemeUtils#theme-utils-get-current-localized-date

I'd hesitate adding this to the theme settings, since it's something that a user is unlikely to ever change once it is configured, and relying on the system locale makes sense to me. 

Please see the docs of the greeter you use to find out how to configure the time format. (It probably is the `time_language` config inside `/etc/lightdm/web-greeter.yml`).
