### ISSUE TITLE
[bug] window.lightdm.show_message._emit is not a function

### ISSUE THREAD

**Issue by Dzordzu** [hertg/lightdm-neon#7]
* **Location**: https://github.com/hertg/lightdm-neon/blob/main/src/signals.ts#L27
* **System**: Arch Linux
* **Versions**:
  - Web greeter 3.4.1 
  - lightdm: 1.32.0
  - lightdm-theme-neon-git: 1:r74.82fcdb7-1

**Comment by Dzordzu** [comment]
```
DevTools listening on ws://127.0.0.1:12345/devtools/browser/30d2e57b-d0cf-4d79-8121-02922311e840
2022-09-16 10:02:21 [ DEBUG ] browser - browser.py:280 : _initialize_devtools | DevTools initialized
2022-09-16 10:02:21 [ DEBUG ] browser - browser.py:250 : init | Browser Window created
2022-09-16 10:02:21 [ DEBUG ] Greeter - Greeter.py:116 : __init__ | LightDM API connected
2022-09-16 10:02:21 [ DEBUG ] browser - browser.py:474 : load_theme | Theme loaded
2022-09-16 10:02:21 [ DEBUG ] browser - browser.py:171 : show | Window is ready
2022-09-16 10:02:21 [ DEBUG ] browser - browser.py:175 : run | Web Greeter started
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
2022-09-16 10:02:32 [ ERROR ] web-greeter://app//usr/share/web-greeter/themes/neon/bundle.js 1: Uncaught TypeError: window.lightdm.show_message._emit is not a function
2022-09-16 10:02:33 [ DEBUG ] browser - browser.py:474 : load_theme | Theme loaded
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by hertg** [comment]
Did you find the bug because you were experiencing issues? Did the error cause the greeter to crash or how did it affect the login process?

Can you check whether the problem also occurs with the latest web-greeter [v3.5.1](https://github.com/JezerM/web-greeter/releases/tag/3.5.1)

Thank you in advance.

**Comment by Dzordzu** [comment]
It was affecting login process. On the incorrect password I was getting error and option to change to "default" theme.

> Can you check whether the problem also occurs with the latest web-greeter [v3.5.1](https://github.com/JezerM/web-greeter/releases/tag/3.5.1)

I wish I could, but [an official package is failing on arch](https://aur.archlinux.org/packages/web-greeter#comment-878893)

Fixed an issue by changing to the nody-greeter

**Comment by Dzordzu** [comment]
@hertg  Thanks for your quick response. As soon as I get web-greeter v3.5.1 I inform you about results

**Comment by Dzordzu** [comment]
Okey. I've managed to update web-greeter. But the issue persists. @hertg maybe you should replace web-greeter with  nody-greeter in the readme? As I've seen in other threads web-greeter is quite problematic

**Comment by hertg** [comment]
I also prefer nody-greeter myself, but I'm unsure what project to prominently link, because web-greeter is the most widely used AFAIK. I run web-greeter on my work laptop and nody-greeter on my personal machine, just to make sure I'd notice a regression, and the theme worked on both fine so far.

Also I don't know what @JezerM's intentions are in terms of supporting web-greeter / nody-greeter / sea-greeter. I'm pinging them so they have an opportunity to chime in on that. It seems like they are consistently updating all of them simultaneously, but I don't know if that may become too much in the long-term, and maybe one or two of the projects may be abandoned sometime in the future to focus on a single one? That's just wild guesses, but I had this uncertainty in my mind for a while now.

> Okey. I've managed to update web-greeter. But the issue persists. @hertg maybe you should replace web-greeter with nody-greeter in the readme? As I've seen in other threads web-greeter is quite problematic

I'm currently linking both, web-greeter and nody-greeter in the README. Maybe I should also link both at the top. Could you link some of those threads that say that web-greeter is "problematic"?

**Comment by JezerM** [comment]
> Also I don't know what @JezerM's intentions are in terms of supporting web-greeter / nody-greeter / sea-greeter.

Well, I'm thinking on maintaining all three for as long as I'm alive or as long as I want. They should be interchangeable with each other, specially with web-greeter and nody-greeter. sea-greeter is still in development (until I got into vacations to finish it), so it's not recommended to be used yet.

> maybe one or two of the projects may be abandoned sometime in the future to focus on a single one?

Perhaps, web-greeter is hurting me with PyQt5 xd But currently, they will all be maintained.

Also, about this issue, the `_emit` method is available only in nody-greeter, and it's not documented neither intended for use within themes. It's an internal method, so @herg, you shouldn't use it.

**Comment by hertg** [comment]
Hey @JezerM, great to hear from you!

Your intentions to support all three as long as possible is very generous, thank you for the continuation of the project(s). Do you have a preference which of the two I should link more prominently in my README?

> Also, about this issue, the _emit method is available only in nody-greeter, and it's not documented neither intended for use within themes.

Thank you for that insight, I will change that. The underscore prefix should have probably tipped me off earlier :wink:

**Comment by JezerM** [comment]
> Do you have a preference which of the two I should link more prominently in my README?

Not really. web-greeter is the most popular, so it could be a great option. However, I think nody-greeter is better designed and more robust. Choose the one you prefer~
